### PR TITLE
Add site

### PR DESCRIPTION
**Pull request by xpbowler**

### CODE REVIEW

**Review by simcard0000 — CHANGES_REQUESTED** [review]
Hey @xpbowler! Don't change [.github/pull_request_template.md](https://github.com/simcard0000/se-webring/pull/40/files#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6b) - that's a template that everyone sees when they make a pull request on GitHub. Rather, you want to add your information to the comment that pulls in the template when you first make your PR. Revert back this file and put the information in the right spot, and then I'll accept your PR. Thanks!

**Comment by xpbowler** [comment]
Okay, thank you!

Full Name: Ryan Nguyen

Cohort Year: 2028

Full website URL: https://rynguyen.com

So we know you're human: 

LinkedIn or a similar profile: https://www.linkedin.com/in/ryan-nguyen-0aa676218/

**Comment by xpbowler** [comment]
I have reverted the pull request template back to the original.

**Review by simcard0000 — APPROVED** [review]
LGTM! 👍🏽

**Pull request merged**
