### PR TITLE
Update sites.js

### PR DESCRIPTION
**Pull request by ericx20**
_To add your site to the webring, you must be a **current student or an alum** of the [undergraduate Software Engineering program at the University of Waterloo](https://uwaterloo.ca/future-students/programs/software-engineering) (Waterloo, ON, Canada)._

**Full Name:** Eric Xu

**Cohort Year:** 2026

**Full website URL:** https://ericxu.net/

_So we know you're human:_

**LinkedIn or a similar profile:** https://www.linkedin.com/in/eric-xu-a726b81a9/

_Don't forget to also add your entry to the end of the_ `allSites` _array in the_ `sites.js` _file (name, year, personal website)!_

### CODE REVIEW

**Review by simcard0000 — CHANGES_REQUESTED** [review]
Thanks Eric! Do you mind putting a link back to the webring somewhere on your website?

**Comment by ericx20** [comment]
@simcard0000 Added, thanks!

**Comment by ericx20** [comment]
Just now I've pushed a fix to the webring logo, the white SVG version. It previously had a white background that made it invisible.

**Review by simcard0000 — APPROVED** [review]
OMG thanks for catching the issue with the SVG! 🎊 Everything LGTM :)

**Pull request merged**
