### PR TITLE
Added website details

### PR DESCRIPTION
**Pull request by granganantjyot**
_To add your site to the webring, you must be a **current student or an alum** of the [undergraduate Software Engineering program at the University of Waterloo](https://uwaterloo.ca/future-students/programs/software-engineering) (Waterloo, ON, Canada)._

**Full Name:** Anantjyot Grang

**Cohort Year:** 2028

**Full website URL:** https://www.anantjyotgrang.com

_So we know you're human:_

**LinkedIn or a similar profile:** https://www.linkedin.com/in/anantjyot-grang/

_Don't forget to also add your entry to the end of the_ `allSites` _array in the_ `se-webring.js` _file (name, year, personal website), and to add the_ `add site` _label to your pull request._

### CODE REVIEW

**Comment by granganantjyot** [comment]
Unable to add 'add site' label to PR :(

**Review by simcard0000 — CHANGES_REQUESTED** [review]
Everything looks ok; except could you add a link-back to the webring somewhere on your site? It can be a text link or an icon link (there are icons in this repo). Thanks! 👍🏽

**Comment by granganantjyot** [comment]
Added link to SE Webring in footer.

**Review by simcard0000 — APPROVED** [review]
Looking good now, thanks!

**Pull request merged**
