### PR TITLE
Update sites.js

### PR DESCRIPTION
**Pull request by Gongsta**
_To add your site to the webring, you must be a **current student or an alum** of the [undergraduate Software Engineering program at the University of Waterloo](https://uwaterloo.ca/future-students/programs/software-engineering) (Waterloo, ON, Canada)._

**Full Name:** Steven Gong

**Cohort Year:** 2026

**Full website URL:** https://stevengong.co/

_So we know you're human:_

**LinkedIn or a similar profile:** https://www.linkedin.com/in/gong-steven/

_Don't forget to also add your entry to the end of the_ `allSites` _array in the_ `sites.js` _file (name, year, personal website)!_

### CODE REVIEW

**Review by simcard0000 — CHANGES_REQUESTED** [review]
Hey Steven! Thanks for your submission - do you think you could add a link back to the webring somewhere on your site?

**Comment by Gongsta** [comment]
Yup, I can add it!

**Comment by simcard0000** [comment]
@Gongsta Just re-request my review once you add the linkback and I'll merge you in :)

**Comment by Gongsta** [comment]
@simcard0000 linked https://stevengong.co/ and here https://stevengong.co/notes/Waterloo-Software-Engineering

**Review by simcard0000 — APPROVED** [review]
Amazing - thanks!

**Pull request merged**
