### PR TITLE
Update se-webring.js

### PR DESCRIPTION
**Pull request by lauraflorea**
_To add your site to the webring, you must be a **current student or an alum** of the [undergraduate Software Engineering program at the University of Waterloo](https://uwaterloo.ca/future-students/programs/software-engineering) (Waterloo, ON, Canada)._

**Full Name:** Laura Florea

**Cohort Year:** 2024

**Full website URL:** https://www.florea.ca/

_So we know you're human:_

**LinkedIn or a similar profile:** https://www.linkedin.com/in/laura-florea/

_Don't forget to also add your entry to the end of the_ `allSites` _array in the_ `se-webring.js` _file (name, year, personal website), and to add the_ `add site` _label to your pull request._

### CODE REVIEW

**Comment by lauraflorea** [comment]
I don't think I have permissions to add labels :(

**Review by simcard0000 — CHANGES_REQUESTED** [review]
See comment on adding a link.

**Comment by lauraflorea** [comment]
@simcard0000 added the link :)

**Review by simcard0000 — APPROVED** [review]
Thanks! :)

**Pull request merged**
